---
name: Check domain name
on: [pull_request_target]
jobs:
  build:
    name: Find substring job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          
      - name: Run bash script
        shell: bash
        run: sh -c .github/actions/find-substring/find-substring.sh
        
      - name: Create Commit Comment, if fail
        if: ${{ failure() }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
            -d '{"body":"Domain name should not be in the source code"}'
